plugins {
    id 'com.android.application'
}

android {
    namespace "com.danielsterling.sterlingsoundaiv4"
    compileSdk 34

    defaultConfig {
        applicationId "com.danielsterling.sterlingsoundaiv4"
        minSdk 24
        targetSdk 34
        versionCode 4
        versionName "1.0.2-PROD"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    signingConfigs {
        release {
            storeFile file(System.getenv("KEYSTORE_FILE") ?: "sterling-sound-upload-key.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    bundle {
        optimizations {
            splitsConfig {
                splitDimension {
                    value = "LANGUAGE"
                    negate = true
                }
            }
        }
        compression {
            uncompressedGlob = ["res/raw/**", "assets/**.uncompressed"]
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.9.0'
    
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
